/* SIX M STORE - Google Sheets Super Shop Backend V2
   Based on SIX_M_STORE_SuperShop_GoogleSheets_V1.
   WhatsApp automatic notification is intentionally NOT included.
*/
const CFG={SHEETS:['Orders','Products','Sales','Expenses','Customers','Admins','Settings','AuditLog','Stock'],DEFAULT_ADMIN_USER:'superadmin',DEFAULT_ADMIN_PASSWORD:'CHANGE-ME-NOW',SESSION_MINUTES:360,LOW_STOCK:5};
function setupSixMStore(){const ss=SpreadsheetApp.getActive();CFG.SHEETS.forEach(n=>{let s=ss.getSheetByName(n)||ss.insertSheet(n);if(s.getLastRow()===0)s.appendRow(headers_(n));s.setFrozenRows(1);});const a=ss.getSheetByName('Admins');if(a.getLastRow()<2)a.appendRow([CFG.DEFAULT_ADMIN_USER,sha256_(CFG.DEFAULT_ADMIN_PASSWORD),'superAdmin','Active',new Date()]);const st=ss.getSheetByName('Settings');const keys=st.getLastRow()?st.getRange(1,1,st.getLastRow(),2).getValues().map(r=>String(r[0]||'')):[];[['STORE_NAME','SIX M STORE'],['DELIVERY_CHARGE','99'],['LOW_STOCK','5']].forEach(r=>{if(!keys.includes(r[0]))st.appendRow(r);});return {ok:true,message:'SIX M STORE V2 database প্রস্তুত'};}
function headers_(n){return({Orders:['orderId','createdAt','customerName','customerPhone','customerAddress','itemsJson','subtotal','deliveryCharge','grandTotal','hasPending','status','source','notes'],Products:['productId','name','brand','size','category','price','stock','active','updatedAt'],Sales:['saleId','createdAt','productId','productName','qty','unitPrice','total','paymentMethod','createdBy','source'],Expenses:['expenseId','createdAt','category','description','amount','createdBy'],Customers:['phone','name','address','firstOrderAt','lastOrderAt','orderCount','totalSpent'],Admins:['username','passwordHash','role','status','createdAt'],Settings:['key','value'],AuditLog:['createdAt','username','action','details'],Stock:['movementId','createdAt','productId','productName','type','quantity','beforeStock','afterStock','reference','notes','createdBy']})[n]||[];}
function doGet(e){try{const p=e.parameter||{},a=p.action||'ping';if(a==='ping')return json_({ok:true,service:'SIX M STORE V2',time:new Date().toISOString()});if(a==='login')return login_(p.username,p.password);const au=auth_(p.token);if(!au.ok)return json_(au);if(a==='dashboard')return dashboard_(au.user);if(['orders','products','sales','expenses','customers','stock','admins'].includes(a)){if(a==='admins'&&au.user.role!=='superAdmin')return json_({ok:false,error:'Super Admin only'});return json_({ok:true,rows:rows_(a==='admins'?'Admins':cap_(a))});}return json_({ok:false,error:'Unknown action'});}catch(err){return json_({ok:false,error:String(err)})}}
function doPost(e){try{const b=JSON.parse(e.postData.contents||'{}'),a=b.action||'';if(a==='createOrder')return createOrder_(b);const au=auth_(b.token);if(!au.ok)return json_(au);const map={saveProduct:()=>saveProduct_(b,au.user),deleteProduct:()=>deleteProduct_(b,au.user),recordSale:()=>recordSale_(b,au.user),recordExpense:()=>recordExpense_(b,au.user),addStock:()=>addStock_(b,au.user),updateOrderStatus:()=>updateOrderStatus_(b,au.user),saveAdmin:()=>saveAdmin_(b,au.user)};return map[a]?map[a]():json_({ok:false,error:'Unknown action'});}catch(err){return json_({ok:false,error:String(err)})}}
function cap_(a){return({orders:'Orders',products:'Products',sales:'Sales',expenses:'Expenses',customers:'Customers',stock:'Stock'})[a]||a;}
function createOrder_(b){const sh=SpreadsheetApp.getActive().getSheetByName('Orders');const now=new Date(),id=b.orderId||'SXM-'+Utilities.formatDate(now,Session.getScriptTimeZone(),'yyyyMMdd-HHmmss');const items=Array.isArray(b.items)?b.items:[];const sub=Number(b.subtotal||0),del=Number(b.deliveryCharge??99),pending=!!b.hasPending,total=pending?'':sub+del;sh.appendRow([id,now,b.customerName||'',b.customerPhone||'',b.customerAddress||'',JSON.stringify(items),sub,del,total,pending,'New',b.source||'Website',b.notes||'']);upsertCustomer_(b.customerName,b.customerPhone,b.customerAddress,pending?0:total,now);return json_({ok:true,orderId:id,status:'New'});}
function login_(u,p){const sh=SpreadsheetApp.getActive().getSheetByName('Admins');if(!sh)return json_({ok:false,error:'Admins sheet নেই. setupSixMStore চালান'});const d=sh.getDataRange().getValues(),h=sha256_(String(p||''));for(let i=1;i<d.length;i++)if(String(d[i][0])===String(u)&&String(d[i][1])===h&&String(d[i][3]).toLowerCase()==='active'){const t=Utilities.getUuid()+'-'+Utilities.getUuid();CacheService.getScriptCache().put('sess_'+t,JSON.stringify({username:d[i][0],role:d[i][2]}),CFG.SESSION_MINUTES*60);audit_(d[i][0],'LOGIN','Admin login');return json_({ok:true,token:t,username:d[i][0],role:d[i][2]});}return json_({ok:false,error:'Username বা Password সঠিক নয়'});}
function auth_(t){if(!t)return{ok:false,error:'Session token প্রয়োজন'};const r=CacheService.getScriptCache().get('sess_'+t);return r?{ok:true,user:JSON.parse(r)}:{ok:false,error:'Session শেষ হয়েছে, আবার Login করুন'};}
function dashboard_(user){const o=rows_('Orders'),p=rows_('Products'),s=rows_('Sales'),e=rows_('Expenses');const today=Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyy-MM-dd');const day=(x)=>String(x||'').slice(0,10)===today;const onlineToday=o.filter(x=>day(x.createdAt)&&x.grandTotal!=='').reduce((a,x)=>a+Number(x.grandTotal||0),0);const salesToday=s.filter(x=>day(x.createdAt)).reduce((a,x)=>a+Number(x.total||0),0);const expToday=e.filter(x=>day(x.createdAt)).reduce((a,x)=>a+Number(x.amount||0),0);const low=p.filter(x=>String(x.active).toLowerCase()!=='no'&&Number(x.stock||0)<=CFG.LOW_STOCK);return json_({ok:true,user,today:{onlineSales:onlineToday,directSales:salesToday,totalSales:onlineToday+salesToday,expenses:expToday,profit:onlineToday+salesToday-expToday},counts:{products:p.length,orders:o.length,pendingOrders:o.filter(x=>!['Delivered','Cancelled'].includes(x.status)).length,customers:rows_('Customers').length},lowStock:low.slice(0,30),recentOrders:o.slice(-10).reverse()});}
function rows_(n){const sh=SpreadsheetApp.getActive().getSheetByName(n);if(!sh||sh.getLastRow()<2)return[];const v=sh.getDataRange().getValues(),h=v[0];return v.slice(1).map(r=>{const o={};h.forEach((k,i)=>o[k]=r[i] instanceof Date?r[i].toISOString():r[i]);return o;});}
function saveProduct_(b,u){const sh=SpreadsheetApp.getActive().getSheetByName('Products'),id=b.productId||'P-'+Date.now().toString().slice(-9),d=sh.getDataRange().getValues();let row=-1;for(let i=1;i<d.length;i++)if(String(d[i][0])===id){row=i+1;break;}const vals=[id,b.name||'',b.brand||'',b.size||'',b.category||'',Number(b.price||0),Number(b.stock||0),b.active===false?'No':'Yes',new Date()];if(row>0)sh.getRange(row,1,1,9).setValues([vals]);else sh.appendRow(vals);audit_(u.username,row>0?'EDIT_PRODUCT':'ADD_PRODUCT',id);return json_({ok:true,productId:id});}
function deleteProduct_(b,u){const sh=SpreadsheetApp.getActive().getSheetByName('Products'),d=sh.getDataRange().getValues();for(let i=1;i<d.length;i++)if(String(d[i][0])===String(b.productId)){sh.getRange(i+1,8).setValue('No');audit_(u.username,'DISABLE_PRODUCT',b.productId);return json_({ok:true});}return json_({ok:false,error:'Product পাওয়া যায়নি'});}
function recordSale_(b,u){const qty=Number(b.qty||0),price=Number(b.unitPrice||0);if(qty<=0||price<0)return json_({ok:false,error:'Quantity/Price ভুল'});const sh=SpreadsheetApp.getActive().getSheetByName('Sales'),id='S-'+Date.now().toString().slice(-9);sh.appendRow([id,new Date(),b.productId||'',b.productName||'',qty,price,qty*price,b.paymentMethod||'Cash',u.username,b.source||'Offline']);if(b.productId)addStock_(Object.assign({},b,{action:'addStock',productId:b.productId,type:'OUT',quantity:qty,reference:id,notes:'Sale'}),u,true);return json_({ok:true,saleId:id,total:qty*price});}
function recordExpense_(b,u){const a=Number(b.amount||0);if(a<=0)return json_({ok:false,error:'Amount দিন'});const id='E-'+Date.now().toString().slice(-9);SpreadsheetApp.getActive().getSheetByName('Expenses').appendRow([id,new Date(),b.category||'Other',b.description||'',a,u.username]);audit_(u.username,'EXPENSE',id);return json_({ok:true,expenseId:id});}
function addStock_(b,u,silent){const sh=SpreadsheetApp.getActive().getSheetByName('Products'),d=sh.getDataRange().getValues();for(let i=1;i<d.length;i++)if(String(d[i][0])===String(b.productId)){const before=Number(d[i][6]||0),q=Math.abs(Number(b.quantity||0)),type=String(b.type||'IN').toUpperCase(),after=type==='OUT'?before-q:before+q;if(after<0)return json_({ok:false,error:'Stock অপর্যাপ্ত'});sh.getRange(i+1,7).setValue(after);const st=SpreadsheetApp.getActive().getSheetByName('Stock');st.appendRow(['M-'+Date.now().toString().slice(-9),new Date(),b.productId,d[i][1],type,q,before,after,b.reference||'',b.notes||'',u.username]);if(!silent)audit_(u.username,'STOCK_'+type,b.productId+' '+q);return json_({ok:true,before,after});}return json_({ok:false,error:'Product পাওয়া যায়নি'});}
function updateOrderStatus_(b,u){const sh=SpreadsheetApp.getActive().getSheetByName('Orders'),d=sh.getDataRange().getValues();for(let i=1;i<d.length;i++)if(String(d[i][0])===String(b.orderId)){sh.getRange(i+1,11).setValue(b.status||'New');audit_(u.username,'ORDER_STATUS',b.orderId+' -> '+b.status);return json_({ok:true});}return json_({ok:false,error:'Order পাওয়া যায়নি'});}
function saveAdmin_(b,u){if(u.role!=='superAdmin')return json_({ok:false,error:'Super Admin only'});if(!b.username||!b.password)return json_({ok:false,error:'Username ও Password দিন'});SpreadsheetApp.getActive().getSheetByName('Admins').appendRow([b.username,sha256_(b.password),b.role||'admin','Active',new Date()]);audit_(u.username,'ADD_ADMIN',b.username);return json_({ok:true});}
function upsertCustomer_(name,phone,address,total,now){if(!phone)return;const sh=SpreadsheetApp.getActive().getSheetByName('Customers'),d=sh.getDataRange().getValues();for(let i=1;i<d.length;i++)if(String(d[i][0])===String(phone)){sh.getRange(i+1,2,1,6).setValues([[name||d[i][1],address||d[i][2],d[i][3]||now,now,Number(d[i][5]||0)+1,Number(d[i][6]||0)+Number(total||0)]]);return;}sh.appendRow([phone,name||'',address||'',now,now,1,Number(total||0)]);}
function audit_(u,a,d){SpreadsheetApp.getActive().getSheetByName('AuditLog').appendRow([new Date(),u,a,d]);}
function sha256_(s){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,s,Utilities.Charset.UTF_8).map(b=>(b<0?b+256:b).toString(16).padStart(2,'0')).join('');}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON);}
