/* SIX M STORE - Google Sheets Super Shop Backend V2 */
const CFG={
  SHEETS:['Orders','Products','Sales','Expenses','Customers','Admins','Settings','AuditLog'],
  DEFAULT_ADMIN_USER:'superadmin',
  DEFAULT_ADMIN_PASSWORD:'CHANGE-ME-NOW',
  SESSION_MINUTES:360
};

function setupSixMStore(){
  const ss=SpreadsheetApp.getActive();
  CFG.SHEETS.forEach(n=>{let s=ss.getSheetByName(n)||ss.insertSheet(n);ensureHeaders_(s,n)});
  const a=ss.getSheetByName('Admins');
  if(a.getLastRow()<2)a.appendRow([CFG.DEFAULT_ADMIN_USER,sha256_(CFG.DEFAULT_ADMIN_PASSWORD),'superAdmin','Active',new Date()]);
  const set=ss.getSheetByName('Settings');
  [['STORE_NAME','SIX M STORE'],['DELIVERY_CHARGE','99'],['ORDER_CHANNEL','Google Sheets Admin']].forEach(x=>{
    if(set.createTextFinder(x[0]).matchCase(true).findNext()==null)set.appendRow(x);
  });
  return json_({ok:true,message:'SIX M STORE database প্রস্তুত হয়েছে'});
}
function headers_(n){return({
 Orders:['orderId','createdAt','customerName','customerPhone','customerAddress','itemsJson','subtotal','deliveryCharge','grandTotal','hasPending','status','source','stockDeducted'],
 Products:['productId','name','brand','size','category','price','stock','active','updatedAt'],
 Sales:['saleId','createdAt','productId','productName','qty','unitPrice','total','paymentMethod','createdBy'],
 Expenses:['expenseId','createdAt','category','description','amount','createdBy'],
 Customers:['phone','name','address','firstOrderAt','lastOrderAt','orderCount','totalSpent'],
 Admins:['username','passwordHash','role','status','createdAt'],Settings:['key','value'],AuditLog:['createdAt','username','action','details']})[n]||[]}
function ensureHeaders_(s,n){const h=headers_(n);if(!h.length)return;if(s.getLastRow()===0){s.appendRow(h);return}const old=s.getRange(1,1,1,s.getLastColumn()).getValues()[0].map(String);h.forEach((x,i)=>{if(old.indexOf(x)<0)s.getRange(1,s.getLastColumn()+1).setValue(x)})}
function doGet(e){try{const p=e.parameter||{},a=p.action||'ping';if(a==='ping')return json_({ok:true,service:'SIX M STORE',time:new Date().toISOString()});if(a==='login')return login_(p.username,p.password);const au=auth_(p.token);if(!au.ok)return json_(au);if(a==='dashboard')return dashboard_(au.user);if(['orders','products','sales','expenses','admins'].includes(a)){if(a==='admins'&&au.user.role!=='superAdmin')return json_({ok:false,error:'Super Admin only'});return json_({ok:true,rows:rows_(a==='orders'?'Orders':a==='products'?'Products':a==='sales'?'Sales':a==='expenses'?'Expenses':'Admins').slice(-500).reverse()})}if(a==='customers')return json_({ok:true,rows:rows_('Customers').slice(-500).reverse()});return json_({ok:false,error:'Unknown action'})}catch(e){return json_({ok:false,error:String(e)})}}
function doPost(e){try{const b=JSON.parse((e.postData&&e.postData.contents)||'{}'),a=b.action||'createOrder';if(a==='createOrder')return createOrder_(b);const au=auth_(b.token);if(!au.ok)return json_(au);if(a==='saveProduct')return saveProduct_(b,au.user);if(a==='bulkSaveProducts')return bulkSaveProducts_(b,au.user);if(a==='recordSale')return recordSale_(b,au.user);if(a==='recordExpense')return recordExpense_(b,au.user);if(a==='updateOrderStatus')return updateOrderStatus_(b,au.user);if(a==='saveAdmin')return saveAdmin_(b,au.user);return json_({ok:false,error:'Unknown action'})}catch(e){return json_({ok:false,error:String(e)})}}
function createOrder_(b){const s=SpreadsheetApp.getActive().getSheetByName('Orders');const id=b.orderId||('SXM-'+Date.now().toString().slice(-8));const items=Array.isArray(b.items)?b.items:[],sub=Number(b.subtotal||0),del=Number(b.deliveryCharge||99),pending=!!b.hasPending,total=pending?'':sub+del;s.appendRow([id,new Date(),b.customerName||'',b.customerPhone||'',b.customerAddress||'',JSON.stringify(items),sub,del,total,pending,'New',b.source||'Website','No']);upsertCustomer_(b.customerName,b.customerPhone,b.customerAddress,pending?0:total,new Date());audit_('Website','NEW_ORDER',id);return json_({ok:true,orderId:id,status:'New'})}
function login_(u,p){const s=SpreadsheetApp.getActive().getSheetByName('Admins'),d=s.getDataRange().getValues(),h=sha256_(String(p||''));for(let i=1;i<d.length;i++)if(String(d[i][0])===String(u)&&String(d[i][1])===h&&String(d[i][3]).toLowerCase()==='active'){const t=Utilities.getUuid()+'-'+Utilities.getUuid();CacheService.getScriptCache().put('sess_'+t,JSON.stringify({username:d[i][0],role:d[i][2]}),CFG.SESSION_MINUTES*60);audit_(u,'LOGIN','Admin login');return json_({ok:true,token:t,username:u,role:d[i][2]})}return json_({ok:false,error:'Username অথবা Password সঠিক নয়'})}
function auth_(t){if(!t)return{ok:false,error:'Session token প্রয়োজন'};const x=CacheService.getScriptCache().get('sess_'+t);return x?{ok:true,user:JSON.parse(x)}:{ok:false,error:'Session শেষ হয়েছে, আবার Login করুন'}}
function dashboard_(u){const p=rows_('Products'),o=rows_('Orders'),s=rows_('Sales'),e=rows_('Expenses');const stock=p.reduce((a,x)=>a+Number(x.stock||0),0),sales=s.reduce((a,x)=>a+Number(x.total||0),0),exp=e.reduce((a,x)=>a+Number(x.amount||0),0),orders=o.filter(x=>x.grandTotal!=='').reduce((a,x)=>a+Number(x.grandTotal||0),0);return json_({ok:true,user:u,counts:{products:p.length,stock,orders:o.length,sales:s.length,expenses:e.length},money:{salesTotal:sales,expenseTotal:exp,orderTotal:orders,net:sales-exp}})}
function rows_(n){const s=SpreadsheetApp.getActive().getSheetByName(n);if(!s||s.getLastRow()<2)return[];const v=s.getDataRange().getValues(),h=v[0];return v.slice(1).map(r=>{const o={};h.forEach((x,i)=>o[x]=r[i] instanceof Date?r[i].toISOString():r[i]);return o})}
function key_(n,b,z){return[String(n||'').trim(),String(b||'').trim(),String(z||'').trim()].join(' | ').toLowerCase()}
function saveProduct_(b,u){return upsertProduct_(b,u)}
function upsertProduct_(b,u){const s=SpreadsheetApp.getActive().getSheetByName('Products'),d=s.getDataRange().getValues(),k=key_(b.name,b.brand,b.size);for(let i=1;i<d.length;i++)if(key_(d[i][1],d[i][2],d[i][3])===k){s.getRange(i+1,6,1,4).setValues([[Number(b.price||0),Number(b.stock||0),b.active===false?'No':'Yes',new Date()]]);audit_(u.username,'UPDATE_PRODUCT',d[i][0]);return json_({ok:true,productId:d[i][0],updated:true})}const id=b.productId||('P-'+Date.now().toString().slice(-8));s.appendRow([id,b.name||'',b.brand||'',b.size||'',b.category||'',Number(b.price||0),Number(b.stock||0),b.active===false?'No':'Yes',new Date()]);audit_(u.username,'SAVE_PRODUCT',id);return json_({ok:true,productId:id})}
function bulkSaveProducts_(b,u){const a=Array.isArray(b.products)?b.products:[];let n=0; a.forEach(x=>{upsertProductSilent_(x,u);n++});audit_(u.username,'IMPORT_PRODUCTS',String(n));return json_({ok:true,count:n})}
function upsertProductSilent_(b,u){const s=SpreadsheetApp.getActive().getSheetByName('Products'),d=s.getDataRange().getValues(),k=key_(b.name,b.brand,b.size);for(let i=1;i<d.length;i++)if(key_(d[i][1],d[i][2],d[i][3])===k){s.getRange(i+1,6,1,4).setValues([[Number(b.price||0),Number(b.stock||0),b.active===false?'No':'Yes',new Date()]]);return}const id='P-'+Utilities.getUuid().slice(0,8);s.appendRow([id,b.name||'',b.brand||'',b.size||'',b.category||'',Number(b.price||0),Number(b.stock||0),b.active===false?'No':'Yes',new Date()])}
function recordSale_(b,u){const q=Number(b.qty||0),p=Number(b.unitPrice||0);if(q<=0||p<0)return json_({ok:false,error:'Quantity/Price ভুল'});const r=changeStock_(b.productId,b.productName,b.brand,b.size,-q);if(!r.ok)return json_(r);const id='S-'+Date.now().toString().slice(-8);SpreadsheetApp.getActive().getSheetByName('Sales').appendRow([id,new Date(),r.productId,b.productName||r.name,q,p,q*p,b.paymentMethod||'Cash',u.username]);audit_(u.username,'CASH_SALE',id);return json_({ok:true,saleId:id,total:q*p,stock:r.stock})}
function changeStock_(id,name,brand,size,delta){const s=SpreadsheetApp.getActive().getSheetByName('Products'),d=s.getDataRange().getValues();for(let i=1;i<d.length;i++){if((id&&String(d[i][0])===String(id))||(!id&&key_(d[i][1],d[i][2],d[i][3])===key_(name,brand,size))){const old=Number(d[i][6]||0),nw=old+delta;if(nw<0)return{ok:false,error:'Stock পর্যাপ্ত নেই। বর্তমান Stock: '+old};s.getRange(i+1,7).setValue(nw);return{ok:true,productId:d[i][0],name:d[i][1],stock:nw}}}return{ok:false,error:'Product পাওয়া যায়নি'}}
function recordExpense_(b,u){const a=Number(b.amount||0);if(a<=0)return json_({ok:false,error:'Expense amount দিন'});const id='E-'+Date.now().toString().slice(-8);SpreadsheetApp.getActive().getSheetByName('Expenses').appendRow([id,new Date(),b.category||'Other',b.description||'',a,u.username]);return json_({ok:true,expenseId:id})}
function updateOrderStatus_(b,u){const s=SpreadsheetApp.getActive().getSheetByName('Orders'),d=s.getDataRange().getValues();for(let i=1;i<d.length;i++)if(String(d[i][0])===String(b.orderId)){let status=b.status||'New';if(status==='Confirmed'&&String(d[i][12]).toLowerCase()!=='yes'){const items=JSON.parse(d[i][5]||'[]');for(const x of items){const r=changeStock_(null,x.name,x.brand,x.size,-Number(x.qty||0));if(!r.ok)return json_(r)}s.getRange(i+1,13).setValue('Yes')}s.getRange(i+1,11).setValue(status);audit_(u.username,'ORDER_STATUS',b.orderId+' -> '+status);return json_({ok:true,status})}return json_({ok:false,error:'Order পাওয়া যায়নি'})}
function saveAdmin_(b,u){if(u.role!=='superAdmin')return json_({ok:false,error:'Super Admin only'});if(!b.username||!b.password)return json_({ok:false,error:'Username ও Password দিন'});const s=SpreadsheetApp.getActive().getSheetByName('Admins'),d=s.getDataRange().getValues();for(let i=1;i<d.length;i++)if(String(d[i][0])===String(b.username))return json_({ok:false,error:'এই Username আগে আছে'});s.appendRow([b.username,sha256_(b.password),b.role||'admin','Active',new Date()]);audit_(u.username,'SAVE_ADMIN',b.username);return json_({ok:true})}
function upsertCustomer_(n,p,a,t,now){if(!p)return;const s=SpreadsheetApp.getActive().getSheetByName('Customers'),d=s.getDataRange().getValues();for(let i=1;i<d.length;i++)if(String(d[i][0])===String(p)){s.getRange(i+1,2,1,6).setValues([[n||'',a||'',d[i][3]||now,now,Number(d[i][5]||0)+1,Number(d[i][6]||0)+Number(t||0)]]);return}s.appendRow([p,n||'',a||'',now,now,1,Number(t||0)])}
function audit_(u,a,d){SpreadsheetApp.getActive().getSheetByName('AuditLog').appendRow([new Date(),u,a,d])}
function sha256_(s){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,s,Utilities.Charset.UTF_8).map(b=>(b<0?b+256:b).toString(16).padStart(2,'0')).join('')}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
